# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectscopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('projectmanager', models.CharField(max_length=100, null=True)),
                ('createdon', models.DateTimeField(default=datetime.datetime.now)),
                ('updatedon', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
