# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDB2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectscopy',
            table='projectscopy',
        ),
    ]
