# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDB2app', '0005_auto_20170710_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectscopy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
